load( ":tilt.bzl", "tilt",)

# Bring up the full set of services for development
tilt(
    name = "up",
    subcmd = "up",
)

# Bring down any remaining/running services
tilt(
    name = "down",
    subcmd = "down",
)

python_bootstrap_binary(
    name = "healthcheck",
    main = "healthcheck.py",
    visibility = ["PUBLIC"],
)

sh_binary(
  name = "update-supergraph",
  main = "bin/update-supergraph.sh",
)

sh_test(
  name = "check-sdl",
  test = "bin/check-sdl.sh",
)

sh_binary(
  name = "init-onchain",
  main = "bin/init-onchain.sh",
)

sh_binary(
  name = "init-user",
  main = "bin/init-user.sh",
)

sh_binary(
  name = "setup-hydra-client",
  main = "bin/setup-hydra-client.sh",
)
